Add Coffeescript support
necinc/msvgc pull request #5
Opened 2017-06-11 13:16 UTC by TheTekton

If anyone wants coffee, this is how you get coffeescript.

2017-06-12 19:26 UTC, maximalism2 requested changes
Could you please pull the master into your branch to take previous PR's updates into this one

2017-06-12 21:13 UTC, TheTekton commented
Sure can, should be all set now.

2017-06-13 04:15 UTC, maximalism2 approved these changes

2017-06-13 04:18 UTC, maximalism2 reviewed
Make small cleanup and will merge this branch

2017-06-13 04:18 UTC, merged